from fastapi import APIRouter
from backend.models.schemas import Insight
from backend.data.mock_data import MOCK_INSIGHTS

router = APIRouter()

@router.get("/insights", response_model=list[Insight], tags=["Insights"])
def get_insights():
    """
    Returns daily domain insight summaries.
    Each insight summarizes what happened in one AI domain recently.
    In production this is generated by the pipeline and stored in Supabase daily_insights.
    """
    return [Insight(**i) for i in MOCK_INSIGHTS]
